FROM golang:1.26-alpine@sha256:a6a091eac01ceac4b97496fe2957a49b6cdd83365337d5f46f6f73710424e805

RUN apk add --no-cache \
    chromium \
    nss \
    freetype \
    harfbuzz \
    ca-certificates \
    sqlite \
    git \
    gcc \
    musl-dev \
    sqlite-dev

ENV ROD_CHROME_PATH=/usr/bin/chromium-browser

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

EXPOSE 80

CMD ["go", "run", "github.com/cosmtrek/air@v1.43.0", \
    "--build.cmd", "CGO_ENABLED=1 go build -o ./screenshot .", \
    "--build.bin", "./screenshot", \
    "--build.delay", "100", \
    "--build.exclude_dir", "", \
    "--build.include_ext", "go,html", \
    "--misc.clean_on_exit", "true"]
