FROM golang:1.27-alpine@sha256:cf6fca6641884b8433441b2b0652976f975e1d0fdd26d177eaaf8596087f3125

RUN apk add --no-cache \
    chromium \
    nss \
    freetype \
    harfbuzz \
    ca-certificates \
    sqlite \
    git \
    gcc \
    musl-dev \
    sqlite-dev

ENV ROD_CHROME_PATH=/usr/bin/chromium-browser

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

EXPOSE 80

CMD ["go", "run", "github.com/cosmtrek/air@v1.43.0", \
    "--build.cmd", "CGO_ENABLED=1 go build -o ./screenshot .", \
    "--build.bin", "./screenshot", \
    "--build.delay", "100", \
    "--build.exclude_dir", "", \
    "--build.include_ext", "go,html", \
    "--misc.clean_on_exit", "true"]
